name: fsrs
description: A Dart package for FSRS, which implements the Free Spaced Repetition Scheduler algorithm. This package assists developers in incorporating FSRS into their flashcard applications.

version: 2.0.0
repository: https://github.com/open-spaced-repetition/dart-fsrs

environment:
  sdk: ^3.3.0

dependencies:
  meta: ^1.17.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
